litmus_governance_spec:
  version: "1.1"
  status: hardened
  immutability:
    declaration: >
      This specification is intentionally narrow and final.
      Any expansion of scope, abstraction, or generality constitutes drift.
    enforcement: >
      Behavior not explicitly described in this document is incorrect.

  identity:
    repository_name: "litmus-governance"
    project_name: "The Litmus Engine"
    internal_tagline: "A senior reviewer that knows when not to speak"
    governing_question: "What would be irresponsible to touch right now?"

  audience_boundary:
    intended_for:
      - Senior engineers inheriting unfamiliar systems
      - Staff and principal engineers accountable for irreversible change
      - Architects performing migration, refactor, or audit risk assessment
    explicitly_not_for:
      - Junior engineers
      - Educational use
      - Skill demonstration
      - Algorithmic sophistication
      - Framework exploration
    exclusion_clause: >
      If the system feels impressive, clever, or educational,
      it is likely incorrect.

  purpose:
    description: >
      Litmus Governance is a deterministic governance system that resolves
      structural information asymmetry before any change is attempted.
    optimization_goal: "Preventing the wrong first change"
    tradeoff: "Precision over exhaustivity"

  execution_boundary:
    nature: "Standalone, single-pass, deterministic analysis"
    input: "Repository snapshot manifest"
    output: "Canonical decision artifacts"
    operating_mode:
      default: advisory
      blocking:
        condition: "Explicit governance configuration only"
        principle: "Blocking is a governance decision, not a tool default"

  non_goals:
    prohibited_capabilities:
      - Risk scoring
      - Ranking or grading repositories
      - Style or lint enforcement
      - Automated refactoring
      - Exhaustive issue detection
      - Optimization recommendations
      - Developer intent inference
      - Psychological or behavioral modeling
    violation_rule: >
      Presence of any prohibited capability renders the system invalid.

  foundational_invariants:
    determinism:
      absolute:
        - No timestamps
        - No randomness
        - No environment leakage
        - Canonical traversal order
        - Canonical serialization
      verification:
        - Identical input produces identical artifacts
        - Identical artifacts produce identical SHA-256 signatures
      failure_mode: >
        Determinism failure must manifest as a hard failure,
        not as degraded output.

    evidence_model:
      allowed_signals:
        - Structural boundaries
        - Configuration and contracts
        - Test presence and coverage
        - Dependency topology
        - Versioning and migration artifacts
      forbidden_signals:
        - Naming interpretation
        - Comment sentiment
        - Runtime speculation
        - Heuristic confidence
        - Behavioral assumptions

    restraint:
      requirements:
        - Severity-gated output
        - Explicit verbosity ceilings
        - Silence as a valid outcome
      rule: >
        Silence requires demonstrated confidence, not absence of analysis.

  cleverness_prohibition:
    rule: >
      Any implementation choice that favors elegance, abstraction,
      extensibility, or reuse over explicitness is incorrect.
    preferences:
      - Duplication over indirection
      - Boring code over clever code
      - Explicit data over inferred behavior

  cognitive_load_constraint:
    rule: >
      A senior engineer must be able to understand the full reasoning model
      in a single uninterrupted reading session.
    violation: >
      If understanding requires revisiting prior sections,
      the system exceeds acceptable complexity.

  incorrectness_visibility:
    invariant: >
      Incorrectness must be obvious without reading documentation.
    detectable_by:
      - Missing artifacts
      - Unstable signatures
      - Non-reproducible output
      - Silent success where refusal is required

  governance_signature:
    definition:
      method: "SHA-256 over canonical artifact bytes"
    properties:
      - Binds output to exact input
      - Auditable
      - Reproducible
      - Non-repudiable
    failure_condition: "Missing or unstable signature"

  refusal:
    definition: "Explicit declaration that no safe action exists"
    mandatory_conditions:
      - Critical paths lack tests or contracts
      - Blast radius cannot be bounded
      - Configuration is contradictory
    rigor_requirement: >
      Refusal must be justified with greater rigor
      than any positive recommendation.

  misleading_signal_restraint:
    requirement: >
      The repository must contain at least one case where
      a naïve tool would escalate and Litmus explicitly does not.
    justification: >
      Restraint must be evidence-anchored and explicit.

  architectural_posture_classification:
    scope: "Structural posture only"
    allowed_basis:
      - Boundary enforcement
      - Governance strictness
      - Migration and deprecation handling
      - Investment asymmetry
    forbidden_basis:
      - Intent inference
      - Velocity assumptions
      - Team behavior modeling
    archetypes:
      - name: "The Pressure Cooker"
        posture: "High-Velocity Instability"
      - name: "The Museum"
        posture: "Stagnant Entropy Hazard"
      - name: "The Construction Site"
        posture: "Guarded Evolution"
      - name: "The Patchwork"
        posture: "Uneven Maturity"
    calibration_effect: >
      Posture applies a severity calibration multiplier.
    temporal_honesty:
      rule: >
        All posture conclusions must declare a validity window.
        Confidence without decay modeling is a defect.

  safe_to_change_surface:
    model: "Risk-aversion boundary, not a score"
    formal_definition:
      universe: "F"
      threshold: "τ"
      condition: "B(f) ≤ τ"
    required_outputs:
      - Explicit safe zones
      - Explicit no-touch zones
      - Evidence references
      - Expiration logic
    mandatory_first_move:
      - Concrete safe first action
      - Or explicit declaration that none exists

  negative_roi_artifact:
    purpose: "Strategic de-prioritization"
    definition: >
      Changes where cost exceeds failure impact by an order of magnitude,
      based on observable invariants.
    required_answers:
      - What not to fix
      - Why it is benign
      - When it ceases to be benign

  uncertainty_handling:
    principles:
      - Localized
      - Calm
      - Explicitly bounded
    rule: >
      Absolutes are forbidden where evidence is partial.

  multi_language_boundary_control:
    primary_language:
      rule: "Exactly one per run"
    secondary_languages:
      scope: "Structural presence only"
    prohibition: >
      Litmus must never claim semantic authority across language boundaries.

  interface:
    ui:
      provided: false
      rule: >
        Decision artifacts are the interface.
        Any interactive UI constitutes scope violation.

  presentation_model:
    canonical_runs:
      requirement: >
        The repository must include committed canonical runs
        demonstrating success, restraint, and refusal.
      structure: "/runs/<case_name>/"
    explanation_rule: >
      Artifacts must be self-evident without prose explanation.

  tone_and_voice:
    requirements:
      - Calm
      - Direct
      - Senior
      - No hype
      - No anthropomorphism
    reference_style: "VP-level technical governance memo"

  definition_of_senior_judgment:
    statement: >
      Senior judgment is the ability to model second-order consequences
      and prioritize structural integrity over feature velocity.
    system_role: >
      Litmus supports this judgment.
      It does not replace it.

  final_litmus_test:
    success_condition: >
      A senior engineer reading the artifacts should think:
      “This is exactly what I would have said.
      And I trust it because it knows when not to speak.”

  narrowness_assertion:
    declaration: >
      The narrowness of this system is intentional.
      It prevents damage instead of producing noise.
